project:
  type: website
  resources:
    - "publications/thumbnails/*.png"
    - "publications/posters/*.pdf"
    - "publications/posters/*.png"
    - CNAME

website:
  title: "Jonas Jürß"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
  twitter-card:
    creator: "@JonasJuerss"
  site-url: https://jonasjuerss.com
  open-graph: true
  page-footer:
    #background: light
    border: true
    left: "© 2024, Jonas Jürß."
    center: ""
    right:
      - icon: github
        href: "https://github.com/jonasjuerss"
      - text: "{{< iconify academicons google-scholar >}}"
        href: "https://scholar.google.com/citations?user=RzWVQVYAAAAJ"
      - text: "{{< iconify academicons dblp >}}"
        href: "https://dblp.uni-trier.de/pid/351/0471.html"
      - icon: linkedin
        href: https://www.linkedin.com/in/jonas-juerss

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



